import AUTHOR_1 from "../../assets/projectAuthor/1.svg";
import PROJECT_1 from "../../assets/projectAuthor/project-1.png";

export const typeBtn = [
  {
    id: 1,
    name: "Education",
    type: "education",
  },
  {
    id: 2,
    name: "Science",
    type: "science",
  },
  {
    id: 3,
    name: "Culture",
    type: "culture",
  },
  {
    id: 4,
    name: "Innovation",
    type: "innovation",
  },
  {
    id: 5,
    name: "Territory development",
    type: "territory-development",
  },
  {
    id: 6,
    name: "Ontology",
    type: "ontology",
  },
  {
    id: 7,
    name: "All",
    type: "all",
  },
];

export const projectsData = [
  {
    id: 1,
    name: "Project Ideas we offer",
    projects: [
      {
        id: 1,
        author: "Peter Nemoy",
        authorImg: AUTHOR_1,
        title: "301 Land of Wisdom",
        flag: 15,
        desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        isSaved: false,
        img: PROJECT_1,
        type: "education",
      },
      {
        id: 2,
        author: "Peter Nemoy",
        authorImg: AUTHOR_1,
        title: "301 Land of Wisdom",
        flag: 15,
        desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        isSaved: false,
        img: PROJECT_1,
        type: "education",
      },
      {
        id: 3,
        author: "Peter Nemoy",
        authorImg: AUTHOR_1,
        title: "301 Land of Wisdom",
        flag: 15,
        desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        isSaved: false,
        img: PROJECT_1,
        type: "science",
      },
      {
        id: 4,
        author: "Peter Nemoy",
        authorImg: AUTHOR_1,
        title: "301 Land of Wisdom",
        flag: 15,
        desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        isSaved: false,
        img: PROJECT_1,
        type: "science",
      },
    ],
  },
  {
    id: 2,
    name: "Projects we fundraise",
    projects: [
      {
        id: 1,
        author: "Peter Nemoy",
        authorImg: AUTHOR_1,
        title: "301 Land of Wisdom",
        flag: 15,
        desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        isSaved: false,
        img: PROJECT_1,
        type: "innovation",
      },
      {
        id: 2,
        author: "Peter Nemoy",
        authorImg: AUTHOR_1,
        title: "301 Land of Wisdom",
        flag: 15,
        desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        isSaved: false,
        img: PROJECT_1,
        type: "territory-development",
      },
      {
        id: 3,
        author: "Peter Nemoy",
        authorImg: AUTHOR_1,
        title: "301 Land of Wisdom",
        flag: 15,
        desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        isSaved: false,
        img: PROJECT_1,
        type: "ontology",
      },
      {
        id: 4,
        author: "Peter Nemoy",
        authorImg: AUTHOR_1,
        title: "301 Land of Wisdom",
        flag: 15,
        desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        isSaved: false,
        img: PROJECT_1,
        type: "education",
      },
      {
        id: 5,
        author: "Peter John",
        authorImg: AUTHOR_1,
        title: "301 Land of Wisdom",
        flag: 15,
        desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        isSaved: false,
        img: PROJECT_1,
        type: "education",
      },
      {
        id: 6,
        author: "Peter Smith",
        authorImg: AUTHOR_1,
        title: "301 Land of Wisdom",
        flag: 15,
        desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        isSaved: false,
        img: PROJECT_1,
        type: "culture",
      },
      {
        id: 7,
        author: "Peter Nemoy",
        authorImg: AUTHOR_1,
        title: "301 Land of Wisdom",
        flag: 15,
        desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        isSaved: false,
        img: PROJECT_1,
        type: "culture",
      },
      {
        id: 8,
        author: "Peter Nemoy",
        authorImg: AUTHOR_1,
        title: "301 Land of Wisdom",
        flag: 15,
        desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        isSaved: false,
        img: PROJECT_1,
        type: "culture",
      },
      {
        id: 9,
        author: "Peter Nemoy",
        authorImg: AUTHOR_1,
        title: "301 Land of Wisdom",
        flag: 15,
        desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        isSaved: false,
        img: PROJECT_1,
        type: "innovation",
      },
      {
        id: 10,
        author: "John Nemoy",
        authorImg: AUTHOR_1,
        title: "301 Land of Wisdom",
        flag: 15,
        desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        isSaved: false,
        img: PROJECT_1,
        type: "innovation",
      },
    ],
  },
  {
    id: 3,
    name: "Projects we Launched",
  },
];
